name: rolling_dicey
description: Application for parsing a dice rolling DSL
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 23.08.02+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  petitparser: ^5.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.5